In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("adult.csv")
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [3]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [4]:
df.shape

(48842, 15)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
 15  income_numeric   48842 non-null  int64
dtypes: int64(7), object(9)
memory usage: 6.0+ MB

In [5]:
df["age"].describe()

count    48842.000000
mean        38.643585
std         13.710510
min         17.000000
25%         28.000000
50%         37.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64

In [6]:
age_list_by_gender = df.groupby("gender")["age"].apply(list)

age_list_by_gender

gender
Female    [18, 24, 26, 43, 37, 34, 72, 56, 26, 28, 52, 5...
Male      [25, 38, 28, 44, 34, 29, 63, 55, 65, 36, 58, 4...
Name: age, dtype: object

In [7]:
grouped_stats = df.groupby("gender")["age"].agg(
    Mean="mean",
    Median="median",
    Minimum="min",
    Maximum="max",
    Standard_Deviation="std"
)

grouped_stats

             Mean  Median  Minimum  Maximum  Standard_Deviation
gender
Female  36.927989    35.0       17       90           14.137423
Male    39.494395    38.0       17       90           13.412850

In [10]:
df["income_numeric"] = df["income"].map({"<=50K": 0, ">50K": 1})

In [14]:
grouped_income = df.groupby(["education", "occupation"])['income_numeric'].agg(
    Mean = "mean", Median="median", Minimum="min", Maximum="max", Standard_Deviation="std"
)
grouped_income

                                   Mean  Median  Minimum  Maximum  \
education    occupation
10th         ?                 0.026667     0.0        0        1
             Adm-clerical      0.000000     0.0        0        0
             Craft-repair      0.096234     0.0        0        1
             Exec-managerial   0.214286     0.0        0        1
             Farming-fishing   0.070423     0.0        0        1
...                                 ...     ...      ...      ...
Some-college Prof-specialty    0.286385     0.0        0        1
             Protective-serv   0.311688     0.0        0        1
             Sales             0.206919     0.0        0        1
             Tech-support      0.234742     0.0        0        1
             Transport-moving  0.263415     0.0        0        1

                               Standard_Deviation
education    occupation
10th         ?                           0.161647
             Adm-clerical                0.000000
             Craft-repair                0.295531
             Exec-managerial             0.415300
             Farming-fishing             0.257679
...                                           ...
Some-college Prof-specialty              0.452426
             Protective-serv             0.463937
             Sales                       0.405232
             Tech-support                0.424336
             Transport-moving            0.441024

[225 rows x 5 columns]

In [17]:
grouped_gain = df.groupby("gender")['capital-gain'].agg(
    Total_Gain = "sum",
    Avg_Gain = "mean",
    Count = "count"
)
grouped_gain

        Total_Gain     Avg_Gain  Count
gender
Female     9403120   580.726285  16192
Male      43300701  1326.208300  32650

In [18]:
grouped_income = df.groupby(["occupation", "education"])['income_numeric'].agg(
    Mean = "mean", Median="median", Minimum="min", Maximum="max", Standard_Deviation="std"
)
grouped_income

                                   Mean  Median  Minimum  Maximum  \
occupation       education
?                10th          0.026667     0.0        0        1
                 11th          0.011050     0.0        0        1
                 12th          0.034483     0.0        0        1
                 1st-4th       0.000000     0.0        0        0
                 5th-6th       0.048780     0.0        0        1
...                                 ...     ...      ...      ...
Transport-moving HS-grad       0.208504     0.0        0        1
                 Masters       0.357143     0.0        0        1
                 Preschool     0.500000     0.5        0        1
                 Prof-school   1.000000     1.0        1        1
                 Some-college  0.263415     0.0        0        1

                               Standard_Deviation
occupation       education
?                10th                    0.161647
                 11th                    0.104825
                 12th                    0.184059
                 1st-4th                 0.000000
                 5th-6th                 0.218085
...                                           ...
Transport-moving HS-grad                 0.406405
                 Masters                 0.497245
                 Preschool               0.707107
                 Prof-school             0.000000
                 Some-college            0.441024

[225 rows x 5 columns]